### ISSUE TITLE
HOTA vs HOTA(0)

### ISSUE THREAD

**Issue by philip-fu** [Zhongdao/UniTrack#10]
Hi,

For evaluation, the HOTA printed out and the HOTA(0) in the csv don't match. What does the '(0)' mean?

Thanks,

**Comment by Zhongdao** [comment]
I think this means the HOTA value at Loc-IoU threshold \alpha=0. The overall HOTA value is an average over HOTA(\alpha) with \alpha from 0 to 1. See [their blog](https://jonathonluiten.medium.com/how-to-evaluate-tracking-with-the-hota-metrics-754036d183e1). I didn't check this though, and always stick with the printed HOTA.

**Comment by philip-fu** [comment]
Got it. Thanks Zhongbao
