### ISSUE TITLE
how to use the DCF head for SOT?

### ISSUE THREAD

**Issue by handworker** [Zhongdao/UniTrack#14]
Hi,
Thanks for your interesting work. Does this code contain the DCF head tracking part? Since I don't find this tracker in the tracker folder.

**Comment by Zhongdao** [comment]
Hi,
Please see this [script](https://github.com/Zhongdao/UniTrack/blob/main/test/test_sot_cfnet.py).
A reminder: the current DCF related code needs a lower version of pytorch, e.g. 1.3.0, because in higher versions like 1.9.0 the APIs of complex number computation have been changed.

**Comment by handworker** [comment]
> Hi,
> Please see this [script](https://github.com/Zhongdao/UniTrack/blob/main/test/test_sot_cfnet.py).
> A reminder: the current DCF related code needs a lower version of pytorch, e.g. 1.3.0, because in higher versions like 1.9.0 the APIs of complex number computation have been changed.

Thanks for your remind. Yes, I find it. I can get the following result:
---------------------------------------------------------------
|     Tracker name     | Success | Norm Precision | Precision |
---------------------------------------------------------------
| imagenet_resnet18_s3 |  0.624  |     0.000      |   0.829   |
---------------------------------------------------------------
This is slightly better than the reported results in Table-2 (a).

For the SiamFC tracker, why don't you use the modified ResNet model architectures provided by Zhipeng Zhang (SiamDW)? This may get the better performance. If I understand correctly, you use the original resnet models (only modify the strides in layer3 and layer4 to 1) for SiamFC trackers.

Thanks for your time.

**Comment by Zhongdao** [comment]
1. Good to see that your result is even slightly better than that in Table-2 (a). There probably exist some subtle differences between the current code/config and in code used for Table-2, but I think it's okay that the results do not match perfectly, as long as the general trends do not change.
2. Re SiamDW: Good point. Here we aim to use an identical representation for different tasks so we do not hope the appearance model is trained for one specific task. Therefore we adopted ImageNet pre-trained weights for each architecture and did not find ImageNet pre-trained weights SiamDW. Of course, we can adopt SiamDW trained for SOT, and hopefully, the performance on SOT could probably be better, but for other tasks, it's hard to say if it would be better.

**Comment by handworker** [comment]
> 1. Good to see that your result is even slightly better than that in Table-2 (a). There probably exist some subtle differences between the current code/config and code used for Table-2, but I think it's okay that the results do not match perfectly, as long as the general trends do not change.
> 2. Re SiamDW: Good point. Here we aim to use an identical representation for different tasks so we do not hope the appearance model is trained for one specific task. Therefore we adopted ImageNet pre-trained weights for each architecture. But we did not find ImageNet pre-trained weights SiamDW. Of course, we can adopt SiamDW trained for SOT, and hopefully, the performance on SOT could probably be better, but for other tasks, it's hard to say if it would be better.

Thanks for your kind explanation. No other probs, I will close this issue.
