### ISSUE TITLE
Bad result on YOLOX + UniTrack demo

### ISSUE THREAD

**Issue by kumi123** [Zhongdao/UniTrack#19]
Hi, Zhangdao
thank you for your wonderful UniTrack framwork. but when i tried use YOLOX + UniTrack demo mot_demo.py on a video sequence,the result was not that good.  i put the yolox_x(the better version) pre-traind model on  yolox/weights and i used the config imagenet_resnet18_s3.yaml .  it seems like the framwork could not detect the person object but works pretty well on other object . by the way i use the default classed arg  list(range(80)) 
what should i do?

![img](https://cdn.jsdelivr.net/gh/kumi123/CDN@latest/img2/result.png)

**Comment by Zhongdao** [comment]
Hi @kumi123，and thanks @kentaroy47！
Already solved (#20)

**Comment by kumi123** [comment]
> Hi @kumi123，and thanks @kentaroy47！ Already solved (#20)

thanks a lot

**Comment by liuyang77712** [comment]
hi @kumi123 , I have a problem.
I also had a bad result like this pic.
![00162](https://user-images.githubusercontent.com/71819201/139788849-0c312a2c-d800-4eb0-8471-d94cb7108dcd.jpg)
I only donwload the yolox_x.pth and run the python demo.
what should i do?
