### ISSUE TITLE
Inference Statistics

### ISSUE THREAD

**Issue by vjsrinivas** [Zhongdao/UniTrack#2]
Hello,

I know this project was just released and some things are still being put up, but do you have any information on the inference speeds for UniTrack with ResNet18 and ResNet50 base appearance models?

**Comment by Zhongdao** [comment]
Hi @vjsrinivas,
Here're my results on the inference speed, all run on a single NVIDIA Titan Xp GPU. 
With ResNet18 as the appearance model, UniTrack runs at ~35 FPS for SOT, ~2 FPS for VOS, and ~10 FPS for MOT/MOTS/PoseTrack. 
With ResNet50 as the appearance model, UniTrack runs at ~15 FPS for SOT, ~1.5 FPS for VOS, and ~3 FPS for MOT/MOTS/PoseTrack.

**Comment by vjsrinivas** [comment]
Thank you!
