### ISSUE TITLE
One Potential Bug

### ISSUE THREAD

**Issue by jimmy-dq** [Zhongdao/UniTrack#24]
Hi Zhongdao,
https://github.com/Zhongdao/UniTrack/blob/e18aece2a9046225ec3b3dd595a35490d594c699/test/test_mot.py#L37
Thanks for your great work to provide such a wonderful evaluation framework!
Recently I have used your framework to test the model on MOT16 (test set). I find when the detection result of a specific frame provided by FairMOT is empty, the 'obs' shown in the above will be also empty and the program will crash. 

Maybe we can re-create a zero matrix obs (1x5) when it is empty (len(obs) = 0). Is it right?

In addition, does your current code provide the VIS evaluation? Since there is no any configurations in your yaml files.

**Comment by Zhongdao** [comment]
Thanks a lot @jimmy-dq ！
In the newest commit, I have solved this bug by checking the size of 'obs'.

Regarding the VIS evaluation:
Yes VIS evaluation is provided, see [this script](https://github.com/Zhongdao/UniTrack/blob/main/test/test_vis.py). Evaluation on VIS is a lit tricky though :)
