### ISSUE TITLE
how to get MOTS-train.txt

### ISSUE THREAD

**Issue by ToumaKazusa3** [Zhongdao/UniTrack#30]
Hi~, How do I get the MOTS-train.txt？

`
Eval Config:
USE_PARALLEL         : False                         
NUM_PARALLEL_CORES   : 8                             
BREAK_ON_ERROR       : True                          
RETURN_ON_ERROR      : False                         
LOG_ON_ERROR         : results/mots/debug/quantitive/error.log
PRINT_RESULTS        : True                          
PRINT_ONLY_COMBINED  : False                         
PRINT_CONFIG         : True                          
TIME_PROGRESS        : True                          
DISPLAY_LESS_PROGRESS : True                          
OUTPUT_SUMMARY       : True                          
OUTPUT_EMPTY_CLASSES : True                          
OUTPUT_DETAILED      : True                          
PLOT_CURVES          : False                         

MOTSChallenge Config:
GT_FOLDER            : /data7/fenghao/dataset/MOTS_unitrack//images/train
TRACKERS_FOLDER      : results/mots/debug/quantitive/..
OUTPUT_FOLDER        : None                          
TRACKERS_TO_EVAL     : ['quantitive']                
CLASSES_TO_EVAL      : ['pedestrian']                
SPLIT_TO_EVAL        : train                         
INPUT_AS_ZIP         : False                         
PRINT_CONFIG         : True                          
TRACKER_SUB_FOLDER   :                               
OUTPUT_SUB_FOLDER    :                               
TRACKER_DISPLAY_NAMES : None                          
SEQMAP_FOLDER        : /data7/fenghao/dataset/MOTS_unitrack//images/train/../../seqmaps
SEQMAP_FILE          : None                          
SEQ_INFO             : None                          
GT_LOC_FORMAT        : {gt_folder}/{seq}/gt/gt.txt   
SKIP_SPLIT_FOL       : True                          
BENCHMARK            : MOTS20                        
no seqmap found: /data7/fenghao/dataset/MOTS_unitrack//images/train/../../seqmaps/MOTS-train.txt
Traceback (most recent call last):
  File "/home/wangwd/.pycharm_helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/wangwd/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/data7/fenghao/UniTrack/test/test_mots.py", line 170, in <module>
    save_videos=opt.save_videos)
  File "/data7/fenghao/UniTrack/test/test_mots.py", line 121, in main
    dataset_list = [trackeval.datasets.MOTSChallenge(dataset_config)]
  File "/data7/fenghao/UniTrack/eval/trackeval/datasets/mots_challenge.py", line 76, in __init__
    self.seq_list, self.seq_lengths = self._get_seq_info()
  File "/data7/fenghao/UniTrack/eval/trackeval/datasets/mots_challenge.py", line 152, in _get_seq_info
    raise TrackEvalException('no seqmap found: ' + os.path.basename(seqmap_file))
eval.trackeval.utils.TrackEvalException: no seqmap found: MOTS-train.txt
python-BaseException

Process finished with exit code 1

`

This is my config
common:
    exp_name: debug
   
    # Model related
    model_type: crw
    remove_layers: ['layer4']
    im_mean: [0.4914, 0.4822, 0.4465]
    im_std: [0.2023, 0.1994, 0.2010]
    nopadding: False
    head_depth: -1
    resume: 'weights/crw.pth'
    
    # Misc
    down_factor: 8
    infer2D: True 
    workers: 4
    gpu_id: 3
    device: cuda

mots:
    obid: 'gt'
    mots_root: '/data7/fenghao/dataset/MOTS_unitrack/'
    save_videos: False
    save_images: False
    test: False
    track_buffer: 30
    nms_thres: 0.4
    conf_thres: 0.5
    iou_thres: 0.5
    prop_flag: False
    max_mask_area: 200
    dup_iou_thres: 0.15
    confirm_iou_thres: 0.7 
    first_stage_thres: 0.7
    feat_size: [4,10]
    use_kalman: True 
    asso_with_motion: True 
    motion_lambda: 0.98 
    motion_gated: False

**Comment by Zhongdao** [comment]
Hi,
MOTS-train.txt is a text file containing a list of MOTS training sequence names. Here is an example:

```

MOTS20-02
MOTS20-05
MOTS20-09
MOTS20-11
```

Note the first line is empty.

**Comment by ToumaKazusa3** [comment]
think you very much~
