### ISSUE TITLE
ImageNet classification pretrain model can not download

### ISSUE THREAD

**Issue by CarlHuangNuc** [Zhongdao/UniTrack#33]
Hi Zhongdao,

        Resnet18,Resnet50 models can not download,

**Comment by Zhongdao** [comment]
Hi,
Could you be more specific about which models can not be downloaded?

**Comment by CarlHuangNuc** [comment]
ImageNet classification | ResNet-50 | .   the links can not work

**Comment by CarlHuangNuc** [comment]
Found from code
