### ISSUE TITLE
ssib info

### ISSUE THREAD

**Issue by Yulv-git** [Zhongdao/UniTrack#43]
https://github.com/Zhongdao/UniTrack/blob/a83e782f5c56c17ccf30f0e330cb50bd3349d5b7/model/model.py#L132
https://github.com/Zhongdao/UniTrack/blob/54347ba1bdba0903b241e00de2b5d0dc3c1a3d14/config/ssib_s3_womotion.yaml#L5
https://github.com/Zhongdao/UniTrack/blob/54347ba1bdba0903b241e00de2b5d0dc3c1a3d14/config/ssib_s3_womotion.yaml#L11

Excuse me, I have not been able to find an introduction to ssib in the paper and code.
What is the full name of ssib, and where do I need to download the pre-trained model of ssib?

Thank you very much!

**Comment by Zhongdao** [comment]
Hi @Yulv-git ,
SSIB is a co-authored work of mine, unpublished yet. Sorry that the paper and code cannot be available in the near future.
Please stay tuned if you are interested!

**Comment by Yulv-git** [comment]
Well, thank you. Look forward to the work and code publication.
