### ISSUE TITLE
Model zoo link doesn't work

### ISSUE THREAD

**Issue by philip-fu** [Zhongdao/UniTrack#9]
Hi, I am trying to use different pretrained models provided by you model zoo but some of the links are empty. And also wondering if you have the im_mean and im_std for each of them.

Thank you,

**Comment by Zhongdao** [comment]
Hi @philip-fu 
I have updated the links, now all models can be downloaded.
Regarding im_mean and im_std:
Most models use an identical setting to ImageNet pre-trained models, i.e. 
```
im_mean = [0.485, 0.456, 0.406]
im_std = [0.229, 0.224, 0.225]
```
Several models use different settings. For example, in CRW
```
im_mean = [0.4914, 0.4822, 0.4465]
im_std = [0.2023, 0.1994, 0.2010]
```
and in UVC/colorization,
```
im_mean = [0.5, 0.5, 0.5]
im_std = [0.5, 0.5, 0.5]
```

**Comment by philip-fu** [comment]
Thanks!!
